CREATE TABLE IF NOT EXISTS contact_message
(
    contact_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       varchar(100) NOT NULL,
    mobile_num varchar(10)  NOT NULL,
    email      varchar(100) NOT NULL,
    subject    varchar(100) NOT NULL,
    message    varchar(500) NOT NULL,
    status     varchar(10)  NOT NULL,
    created_at timestamp    NOT NULL,
    created_by varchar(50)  NOT NULL,
    updated_at timestamp   DEFAULT NULL,
    updated_by varchar(50) DEFAULT NULL
);
