version: '3.9'

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_DATABASE: "testdb"
      MYSQL_USER: "admin"
      MYSQL_PASSWORD: "12345678"
      MYSQL_ROOT_PASSWORD: "rootroot"
    ports:
      - "3306:3306"
#    expose:
#      - "3306"
    volumes:
      - ./init-db:/docker-entrypoint-initdb.d
      - mysql_volume:/var/lib/mysql

volumes:
  mysql_volume: